version: 2
updates:
- package-ecosystem: elm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.2.0
    - 5.2.2
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.9.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
  - dependency-name: elm
    versions:
    - 0.19.1-4
  - dependency-name: webpack-dashboard
    versions:
    - 3.3.0
